name: 'Promote a Google Play App from one track to another'
description: "Promote a Google Play App from one track to another"
author: 'The Vincit Group'
inputs:
  serviceAccountJsonPlainText:
    description: "The plain text of the service account json used to for authorization"
    required: true
  packageName:
    description: "The package name of the app you are promoting"
    required: true
  fromTrack:
    description: "The track you are promoting from"
    required: true  
  toTrack:
    description: "The track you are promoting to"
    required: true
  testOnly:
    description: "For testing, do not perform commit after promoting"
    default: 'false'
    required: false
runs:
  using: 'node12'
  main: 'src/index.js'
