name: Promote Track
description: Promote a Google Play App from one track to another
inputs:
  serviceAccountJson:
    description: "Path of the service account json used to for authorization"
    required: false
  serviceAccountJsonPlainText:
    description: "The plain text of the service account json used to for authorization"
    required: false
  packageName:
    description: "The package name of the app you are promoting"
    required: true
  fromTrack:
    description: "The track you are promoting from"
    required: true  
  toTrack:
    description: "The track you are promoting to"
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
